version: '2.4'

services:
  python-server:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: python-server
    container_name: python-server
    command: bash
    stdin_open: true
    tty: true
    volumes:
      - ./:/apps

